### ISSUE TITLE
[help] setup username and password and default db

### ISSUE THREAD

**Issue by u007** [tericcabrel/blog-tutorials#3]
hi,

sorry to trouble you , great example ! :)

i tried to setup username n password by adding 
```
environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=example"
```

but i could not login via my mongodb client
if i didnt set this, i can go into the instant mongo1 without any userid n password

**Comment by tericcabrel** [comment]
Hi 
Sorry to reply late, but have you managed to solve your issue? 
What blog post is this issue about?

**Comment by u007** [comment]
sorry i cant recall anymore lol
