### ISSUE TITLE
next-api-middleware is now out of date

### ISSUE THREAD

**Issue by pickled-cucumber** [tericcabrel/blog-tutorials#4]
Next.js has changed the way middleware is handled and the blog post is now out of date. Source: https://nextjs.org/docs/advanced-features/middleware

**Comment by tericcabrel** [comment]
Thank you! I will update it

**Comment by tericcabrel** [comment]
Hey, @pickled-cucumber, this is the update: 

[https://blog.tericcabrel.com/protect-your-api-routes-in-next-js-with-middleware](https://blog.tericcabrel.com/protect-your-api-routes-in-next-js-with-middleware)

Thank you again.
