### ISSUE TITLE
How to create secret key

### ISSUE THREAD

**Issue by hendisantika** [tericcabrel/blog-tutorials#9]
How to create secret key like this?
```
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
```

**Comment by tericcabrel** [comment]
Hello 👋🏾 
You can use this website [https://www.devglan.com/online-tools/hmac-sha256-online](https://www.devglan.com/online-tools/hmac-sha256-online)
